<a href="https://colab.research.google.com/github/emredeveloper/Data-Preprocessing/blob/master/KNNImputer_Eksik_veri_doldurma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Örnek veri seti oluşturma
np.random.seed(0)
data = np.random.rand(10, 5)  # 10 satır, 5 sütunlu rastgele veri seti
data[np.random.rand(10, 5) < 0.2] = np.nan  # %20 oranında eksik veri oluştur

# KNN Imputation
knn_imputer = KNNImputer(n_neighbors=2)
data_knn_imputed = knn_imputer.fit_transform(data)
print("KNN Imputed Data:")
print(data_knn_imputed)

# MissForest Imputation
# Öncelikle RandomForestClassifier eğitimi ve eksik verili veri setinin düzeltilmesi
model = RandomForestClassifier(n_estimators=100, random_state=0)
X = pd.DataFrame(data_knn_imputed)  # KNN ile doldurulmuş veri seti bir DataFrame'e dönüştürüldü
X = X.fillna(X.mean())  # Eksik değerler yerine ortalama değerler doldurulabilir

# Modeli eğitme (örnek olarak)
y = np.random.randint(0, 2, 10)  # Gözlem sınıfları (örnek veri için)
model.fit(X, y)

# Yeni veri setinde eksik değerleri doldurma
X_imputed = model.predict(X)

# Basit accuracy hesaplama (örnek olarak)
y_pred = model.predict(X)
accuracy = accuracy_score(y, y_pred)
print(f"Accuracy after Imputation: {accuracy}")



KNN Imputed Data:
[[0.5488135  0.71518937 0.60276338 0.95370542 0.4236548 ]
 [0.5832245  0.43758721 0.891773   0.96366276 0.38344152]
 [0.76371592 0.75717397 0.56804456 0.87209597 0.27096461]
 [0.0871293  0.0202184  0.74726819 0.77815675 0.20111566]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.2233186  0.14335329 0.67662618 0.52184832 0.52510412]
 [0.26455561 0.77423369 0.74726819 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.74726819 0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.74726819 0.06022547 0.66676672]
 [0.2233186  0.21038256 0.74726819 0.31542835 0.34277826]]
Accuracy after Imputation: 1.0


In [2]:
data

array([[0.5488135 , 0.71518937, 0.60276338,        nan, 0.4236548 ],
       [       nan, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [       nan,        nan, 0.56804456,        nan,        nan],
       [0.0871293 , 0.0202184 ,        nan, 0.77815675,        nan],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [       nan, 0.14335329,        nan, 0.52184832,        nan],
       [0.26455561, 0.77423369,        nan, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572,        nan, 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195,        nan, 0.06022547, 0.66676672],
       [       nan, 0.21038256,        nan, 0.31542835,        nan]])